# Generated by Django 5.2.1 on 2025-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_restock_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restock',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='restock',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
