# Generated by Django 5.2.1 on 2025-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_restock_date_created_alter_restock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
