# Generated by Django 5.2.1 on 2025-07-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_medication_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
