# Generated by Django 5.2.1 on 2025-08-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_custom_id_sale_custom_id'),
    ]

    operations = [
    ]
