# Generated by Django 5.2.1 on 2025-08-02 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enhance_prescription_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='prescription',
            name='administration_route',
            field=models.CharField(default='Oral', help_text='e.g., Oral, Topical, Injection', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='allergies',
            field=models.TextField(blank=True, help_text='Patient allergies', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='copay_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='digital_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='quantity_dispensed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='quantity_prescribed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refills_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refills_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='', help_text='e.g., 500mg', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(default='', help_text='e.g., 7 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(default='', help_text='e.g., Twice daily', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.medication'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_by',
            field=models.CharField(default='', help_text="Doctor's name", max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('dispensed', 'Dispensed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', 'priority'], name='core_prescr_status_41bb98_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescribed_date'], name='core_prescr_prescri_f71871_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['customer', 'status'], name='core_prescr_custome_b3f0b1_idx'),
        ),
    ]
