# Generated by Django 5.2.3 on 2026-04-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='audittrail',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
                ),
                migrations.AlterField(
                    model_name='prescription',
                    name='created_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to='core.user'),
                ),
                migrations.AlterField(
                    model_name='prescription',
                    name='verified_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to='core.user'),
                ),
                migrations.AlterField(
                    model_name='stockmovement',
                    name='created_by',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
                ),
            ],
        ),
    ]
