# Generated by Django 5.2.1 on 2026-04-11 01:00

from django.db import migrations, connections


def fix_audittrail_fk(apps, schema_editor):
    """Fix AuditTrail foreign key to use core_user instead of auth_user."""
    # Only run on PostgreSQL - SQLite doesn't support CONSTRAINT operations
    if schema_editor.connection.vendor != 'postgresql':
        return  # Skip on SQLite
    
    with connections['default'].cursor() as cursor:
        # Drop the existing FK constraint
        cursor.execute("""
            ALTER TABLE core_audittrail 
            DROP CONSTRAINT IF EXISTS "core_audittrail_user_id_ba0edbb5_fk_auth_user_id";
        """)
        
        # Clear the data
        cursor.execute("DELETE FROM core_audittrail;")
        
        # Drop and recreate the column with UUID type
        cursor.execute("""
            ALTER TABLE core_audittrail
            DROP COLUMN user_id;
        """)
        
        cursor.execute("""
            ALTER TABLE core_audittrail
            ADD COLUMN user_id uuid;
        """)
        
        # Add the new FK constraint pointing to core_user
        cursor.execute("""
            ALTER TABLE core_audittrail
            ADD CONSTRAINT core_audittrail_user_id_fkey
            FOREIGN KEY (user_id)
            REFERENCES core_user(id)
            ON DELETE CASCADE;
        """)


def reverse_fix(apps, schema_editor):
    """Reverse the migration - restore auth_user FK."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    with connections['default'].cursor() as cursor:
        cursor.execute("""
            ALTER TABLE core_audittrail
            DROP CONSTRAINT IF EXISTS core_audittrail_user_id_fkey;
        """)
        
        cursor.execute("DELETE FROM core_audittrail;")
        
        cursor.execute("""
            ALTER TABLE core_audittrail
            DROP COLUMN user_id;
        """)
        
        cursor.execute("""
            ALTER TABLE core_audittrail
            ADD COLUMN user_id bigint;
        """)
        
        cursor.execute("""
            ALTER TABLE core_audittrail
            ADD CONSTRAINT "core_audittrail_user_id_ba0edbb5_fk_auth_user_id"
            FOREIGN KEY (user_id)
            REFERENCES auth_user(id)
            ON DELETE CASCADE;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RunPython(fix_audittrail_fk, reverse_fix),
    ]
