# Generated by Django 5.2.1 on 2026-04-20 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fix_audittrail_fk_to_core_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restock',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.UniqueConstraint(fields=('name', 'batch_no'), name='unique_medication_name_batch'),
        ),
    ]
