# Generated by Django 5.2.1 on 2026-04-26 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fix_admin_log_user_id_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'attempt_time'], name='core_failed_usernam_aecc43_idx'), models.Index(fields=['ip_address', 'attempt_time'], name='core_failed_ip_addr_8f7e88_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('status_code', models.IntegerField(null=True)),
                ('response_time_ms', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='core_apireq_ip_addr_e6e2b2_idx'), models.Index(fields=['user', 'timestamp'], name='core_apireq_user_id_53b2a6_idx'), models.Index(fields=['endpoint', 'timestamp'], name='core_apireq_endpoin_dd39e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('invalid_token', 'Invalid Token'), ('unauthorized_access', 'Unauthorized Access')], max_length=50)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='core_securi_event_t_72c930_idx'), models.Index(fields=['user', 'timestamp'], name='core_securi_user_id_8e89f8_idx')],
            },
        ),
    ]
