# Generated by Django 5.2.17 on 2026-08-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_businessday'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='classification',
            field=models.CharField(blank=True, choices=[('Antibiotics', 'Antibiotics'), ('Antifungals', 'Antifungals'), ('Antidiabetic', 'Antidiabetic'), ('Pain reliever', 'Pain reliever'), ('Antihistamine & allergy', 'Antihistamine & allergy'), ('Cardiovascular medications', 'Cardiovascular medications'), ('Antidepressants', 'Antidepressants'), ('Respiratory medications', 'Respiratory medications'), ('Sleep aids', 'Sleep aids'), ('Hormonal medications', 'Hormonal medications'), ('Gastrointestinal medication', 'Gastrointestinal medication'), ('Anticoagulants', 'Anticoagulants'), ('Anticonvulsants', 'Anticonvulsants'), ('Antipsychotics', 'Antipsychotics')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='category',
            field=models.CharField(choices=[('Herbal', 'Herbal'), ('Suspension', 'Suspension'), ('Syrup', 'Syrup'), ('Tablets', 'Tablets'), ('Soluble', 'Soluble'), ('Capsules', 'Capsules'), ('Ointment', 'Ointment'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('Gel and cream', 'Gel and cream'), ('Antiseptics', 'Antiseptics'), ('Oil', 'Oil'), ('Contraceptives', 'Contraceptives'), ('Infusion', 'Infusion'), ('Injectables', 'Injectables')], max_length=100),
        ),
    ]
