# Generated by Django 5.2.17 on 2026-08-27 02:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sale_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprofile',
            name='tax_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0300'), help_text='Fractional rate, e.g. 0.03 = 3%', max_digits=6),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
    ]
