# Generated by Django 5.2.17 on 2026-08-27 02:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sale_pharmacy_tax_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('license_no', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('tax_enabled', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0300'), help_text='Fractional rate, e.g. 0.03 = 3%', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='medication',
            name='unique_medication_name_batch',
        ),
        migrations.AlterField(
            model_name='businessday',
            name='business_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0300'), max_digits=6),
        ),
        migrations.AddField(
            model_name='businessday',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_days', to='core.branch'),
        ),
        migrations.AddField(
            model_name='medication',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='core.branch'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='core.branch'),
        ),
        migrations.AddField(
            model_name='restock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restocks', to='core.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches this user can access (admins may access all).', related_name='users', to='core.branch'),
        ),
        migrations.AddIndex(
            model_name='businessday',
            index=models.Index(fields=['branch', 'status'], name='core_busine_branch__040934_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessday',
            constraint=models.UniqueConstraint(fields=('branch', 'business_date'), name='unique_business_day_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.UniqueConstraint(fields=('branch', 'name', 'batch_no'), name='unique_medication_branch_name_batch'),
        ),
    ]
